#!/bin/bash

APP=/usr/bin/iptrestdaemon
LOGS=/var/log/iptrest.log
PIDFILE=/var/run/iptrest.pid

function checkpidfile() {
    local PID=
    PID="$(cat $PIDFILE 2> /dev/null | head -n 1)"
    if [ "$PID" != "" ]; then
        if ps "$PID" 2> /dev/null > /dev/null; then
            return 1
        else
            rm "$PIDFILE"
        fi
    fi
    return 0
}

function killprocess() {
    local PID=
    PID="$(cat $PIDFILE 2> /dev/null | head -n 1)"
    if [ "$PID" != "" ]; then
        kill "$PID"
        sleep 1
        if ps "$PID" 2> /dev/null > /dev/null; then
            return 1
        fi
        rm "$PIDFILE" 2> /dev/null
    fi
    return 0
}

function start() {
    if checkpidfile; then
        $APP >> $LOGS 2>> $LOGS &
        if [ $? -eq 0 ]; then
            CHILD=$!
            echo "$CHILD" > "$PIDFILE"
            if [ $? -ne 0 ]; then
                echo "could not write the pidfile"
            fi
            echo "daemon started"
        else
            echo "could not start the application"
            return 1
        fi
    else
        echo "daemon already running"
        return 1
    fi    
}

function status() {
    if checkpidfile; then
        echo "daemon not running"
        return 1
    else
        echo "daemon running"
        return 0
    fi    
}

function stop() {
    if checkpidfile; then
        echo "daemon not running"
        return 1
    else
        if killprocess; then
            echo "daemon stopped"
            return 0
        else
            echo "could not stop daemon"
            return 2
        fi
    fi    
}

case $1 in
    start)  start
            exit $?
            ;;
    status) status
            exit $?
            ;;
    stop)   stop
            exit $?
            ;;
    restart)
            stop
            [ $? -gt 1 ] && exit 1
            start
            exit $?
            ;;
esac